- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: narasimha-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter Trainer name
    private: false
  tasks:
  - name: variable at task level
    vars:
      NAME: narasimha-task
    ansible.builtin.debug:
      msg: "Trainer name is: {{NAME}}"

      # 1St  is command line
      # 2nd preference is level
      # 3rd preference is vars_files
      # 4th preferance is prompt
      # 5th preferance is play
      # 6th preferance is inventory
      #  7th preferance is roles
      