- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    # list of packages
    loop:
    - nginx
    - postmap
    - postfix
    - cyrus-sasl-plain
    - mailx